#' @title Make Presence/Absence Data Frame for Modeling
#'
#' @description This is a wrapper function for \code{merge_spp_env}, \code{match_guilds}, \code{remove_corr}, and \code{set_binary_pa} that produces logs and has skip functionality to assist in running multiple species in parallel.

#' @param name Species name to add to log files and save data to correct directory (see vignette for recommended directory set up)
#' @param skip TRUE/FALSE indicating whether to skip creating the raster file if file already exists
#' @param m_min,m_max,y_min,y_max (m)onth and (y)ear ranges to help create names for combined rasterBrick since they aren't always retained and these are necessary for matching fisheries and environmental data

#' @return does not return anything to the environment; it only saves the data sets generated by each step and writes to the log file

make_pa_df_wrapper <- function(name, skip, m_min, m_max, y_min, y_max) {
  sink(file.path(getwd(), 'logs', 'build_data_frames.log'), append = T)
  # Ensure the sinks are closed when the function exits, regardless of how it exits.
  on.exit({
    #sink(type = "message")
    sink()
  })

  print(Sys.time())
  print(name)

  if (skip) {
    if (
      file.exists(paste(file.path(getwd(), name), 'pa_clean.RData', sep = '/'))
    ) {
      print('file exists and skip == T, so skipping this species!')
      return(NA)
    } else {
      combinedRasts <- raster::brick(paste(
        file.path(getwd(), name, 'input_rasters'),
        'combined_rasters.nc',
        sep = '/'
      )) #combinedRasts

      my <- expand.grid(m_min:m_max, y_min:y_max)
      names(combinedRasts) <- paste(
        sprintf("%02d", my$Var1),
        my$Var2,
        sep = '.'
      )

      print(paste0(name, '- merging pa and model data -', Sys.time()))
      df <- match_pa_model_rasters(
        pa_rasters = combinedRasts,
        model_data = norm,
        add_static = TRUE,
        static_variables = staticVars
      )
      save(
        df,
        file = paste(
          file.path(getwd(), name),
          'presence_absence_environment.RData',
          sep = '/'
        )
      )

      print(paste0(name, '- matching guild -', Sys.time()))

      dfG <- match_guilds(
        spp_env = df,
        spp = name,
        spp_col = 'SCI_NAME',
        spp_guild = 'spp_list.csv',
        feeding_key = 'feeding_guilds.csv',
        feeding_col = 'Feeding.Guild',
        habitat_key = 'habitat_guilds.csv',
        habitat_col = 'Habitat.Guild',
        static_vars = c(
          'x',
          'y',
          'month',
          'year',
          'bathy',
          'rugosity',
          'dist2coast'
        ),
        pa_col = 'value'
      )
      save(
        dfG,
        file = paste(file.path(getwd(), name), 'pa_guild.RData', sep = '/')
      )

      print(paste0(name, '- converting to binary -', Sys.time()))
      dfB <- set_binary_pa(dfG, pa_col = 'value')
      save(
        dfB,
        file = paste(file.path(getwd(), name), 'pa_binary.RData', sep = '/')
      )

      print(paste0(name, ' - removing correlated variables -', Sys.time()))
      dfC <- remove_corr(
        dfB,
        pa_col = 'value',
        xy_col = c('x', 'y'),
        month_col = 'month',
        year_col = 'year'
      )
      save(
        dfC,
        file = paste(file.path(getwd(), name), 'pa_clean.RData', sep = '/')
      )
    }
  } else {
    combinedRasts <- raster::brick(paste(
      file.path(getwd(), name, 'input_rasters'),
      'combined_rasters.nc',
      sep = '/'
    )) #combinedRasts

    my <- expand.grid(m_min:m_max, y_min:y_max)
    names(combinedRasts) <- paste(sprintf("%02d", my$Var1), my$Var2, sep = '.')

    print(paste0(name, '- merging pa and model data -', Sys.time()))
    df <- match_pa_model_rasters(
      pa_rasters = combinedRasts,
      model_data = norm,
      add_static = TRUE,
      static_variables = staticVars
    )
    save(
      df,
      file = paste(
        file.path(getwd(), name),
        'presence_absence_environment.RData',
        sep = '/'
      )
    )

    print(paste0(name, '- matching guild -', Sys.time()))

    dfG <- match_guilds(
      spp_env = df,
      spp = name,
      spp_col = 'SCI_NAME',
      spp_guild = 'spp_list.csv',
      feeding_key = 'feeding_guilds.csv',
      feeding_col = 'Feeding.Guild',
      habitat_key = 'habitat_guilds.csv',
      habitat_col = 'Habitat.Guild',
      static_vars = c(
        'x',
        'y',
        'month',
        'year',
        'bathy',
        'rugosity',
        'dist2coast'
      ),
      pa_col = 'value'
    )
    save(
      dfG,
      file = paste(file.path(getwd(), name), 'pa_guild.RData', sep = '/')
    )

    print(paste0(name, '- converting to binary -', Sys.time()))
    dfB <- set_binary_pa(dfG, pa_col = 'value')
    save(
      dfB,
      file = paste(file.path(getwd(), name), 'pa_binary.RData', sep = '/')
    )

    print(paste0(name, ' - removing correlated variables -', Sys.time()))
    dfC <- remove_corr(
      dfB,
      pa_col = 'value',
      xy_col = c('x', 'y'),
      month_col = 'month',
      year_col = 'year'
    )
    save(
      dfC,
      file = paste(file.path(getwd(), name), 'pa_clean.RData', sep = '/')
    )
  }
}
