#' @title Prepare Fisheries and Environmental Data for Modeling
#'
#' @description This is a wrapper function for \code{match_fisheries_environment_data}, and \code{remove_corr} that produces logs and has skip functionality to assist in running multiple species in parallel. This function also subsets the data into training and test datasets based on provided years

#' @param name Species name to add to log files and save data to correct directory (see vignette for recommended directory set up)
#' @param source 'hindcast' or 'forecast' to determine which MOM6 rasters to use based on naming convention
#' @param short_names a vector of shorthand names for variable to help pull desired environmental data based on naming convention
#' @param release release code for MOM6 data to help pull desired environmental data based on naming convention
#' @param init initialization code for MOM6 forecast data to help pull desired environmental data based on naming convention
#' @param spatial_temporal TRUE/FALSE to determine method for normalizing. Helps pull desired environmental data based on naming convention
#' @param mask_bathy TRUE/FALSE indicating whether or not to use bathymetry data as a mask for raw data. Helps pull desired environmental data based on naming convention
#' @param add_static TRUE/FALSE to add static variables such as bathymetry. If TRUE, static_variables needs to be supplied.
#' @param static_variables a spatRaster containing static variables such as bathymetry. Each layer should be named. Used in \code{match_fisheries_environment_data}
#' @param rm_corr TRUE/FALSE to test for correlated environmental covariates and remove them from the data frame if necessary
#' @param training_years,test_years vectors each with a length of 2, indicating the ranges of years that should be used to split the training and test datasets
#' @param skip TRUE/FALSE to test if training and test datasets already exist. If they do, the run is skipped. 
#' @param force_overwrite TRUE/FALSE designating whether or not to force the function to overwrite the existing file. Overrides skip and sets skip = FALSE. Defaults to FALSE. 

#' @return does not return anything to the environment; it only saves the data sets generated by each step and writes to the log file

prepare_dataframe_wrapper <- function(name, source, short_names, release, spatial_temporal, mask_bathy, all_env = F, spp_key, hab_key, feed_key, add_static = T, static_variables, rm_corr = T, training_years, test_years, skip = F, force_overwrite = F){
  
  #step 0 - set up suffixes & logging
  suffix <- if(spatial_temporal) "" else "_global"
  bathy_suffix <- if(mask_bathy) "masked" else ""
  corr_suffix <- if(rm_corr) "rmcorr" else ""
  
  log_path <- file.path(getwd(), 'logs', 'prepare_dataframes.log')
  log_appender(appender_file(log_path))
  
  # Define final output paths up front
  species_dir <- file.path(getwd(), name)
  training_name <- file.path(species_dir, paste0('training_', training_years[1], '_', training_years[2], '_', corr_suffix, '_', source, '_', release, '_', bathy_suffix, suffix, '.csv'))
  test_name     <- file.path(species_dir, paste0('test_', test_years[1], '_', test_years[2], '_', corr_suffix, '_', source, '_', release, '_', bathy_suffix, suffix, '.csv'))
  
  # Check if files exist and we are skipping
  if (skip && !force_overwrite && file.exists(training_name) && file.exists(test_name)) {
    log_info("{name}: Training and test files already exist. Skip is TRUE. Skipping execution.")
    return(NA)
  } 
  
  if (force_overwrite && (file.exists(training_name) || file.exists(test_name))) {
    log_info("{name}: Output files exist, but force_overwrite is TRUE. Overwriting previous runs...")
  }
  
  log_info("{name}: Beginning data preparation pipeline...")
  
  # --- Step 1: Load Environmental Rasters ---
  env_rasters <- tryCatch({
    rasters <- vector(mode = 'list', length = length(short_names))
    for (x in seq_along(short_names)) {
      raster_path <- paste0('./Data/MOM6/norm_', short_names[x], '_', source, '_', release, '_', bathy_suffix, suffix, '.tif')
      if (!file.exists(raster_path)) stop(paste("Missing upstream raster:", raster_path))
      rasters[[x]] <- terra::rast(raster_path)
    }
    names(rasters) <- short_names
    rasters
  }, error = function(e) {
    log_error("{name}: Failed to load environmental rasters: {e$message}")
    return(NULL)
  })
  
  if (is.null(env_rasters)) return(NULL) # Graceful early exit
  
  # --- Step 1.5: Subset Rasters by Guild Key (Memory Saver) ---
  if (!all_env) {
    env_rasters <- tryCatch({
      log_info("{name}: Subsetting environmental data based on guilds...")
      g <- which(spp_key$Name %in% name)
      if (length(g) == 0) stop("Species not found in spp_key dataframe.")
      
      fGuild <- spp_key[g, 'Feeding.Guild']
      hGuild <- spp_key[g, 'Habitat.Guild']
      
      i <- which(colnames(feed_key) == fGuild)
      fInd <- feed_key[nzchar(feed_key[, i]), i]
      
      i <- which(colnames(hab_key) == hGuild)
      hInd <- hab_key[nzchar(hab_key[, i]), i]
      
      ind <- names(env_rasters) %in% c(unlist(as.vector(fInd)), unlist(as.vector(hInd)))
      env_rasters[ind]
    }, error = function(e) {
      log_warn("{name}: Guild subsetting failed ({e$message}). Defaulting to all environmental rasters.")
      env_rasters # Fall back to using all rasters if subsetting crashes
    })
  }
  
  # --- Step 2: Match Fisheries and Environmental Data ---
  matched_df <- tryCatch({
    log_info("{name}: Matching fisheries presence-absence with MOM6 rasters...")
    
    # 2.1 Handle Parallel Safe Unwrapping of Static Rasters
    if (add_static && inherits(static_variables, "PackedSpatRaster")) {
      static_variables <- terra::unwrap(static_variables)
    }
    
    pa_path <- file.path(species_dir, 'input_csvs', 'combined_pa.csv')
    if (!file.exists(pa_path)) stop(paste("Species occurrence file missing at path:", pa_path))
    spp_pa <- read.csv(pa_path)
    
    df <- match_fisheries_environment_data(
      species_df = spp_pa,
      model_data = env_rasters,
      add_static = add_static,
      static_variables = static_variables
    )
    
    dir.create(species_dir, recursive = TRUE, showWarnings = FALSE)
    matched_out_path <- file.path(species_dir, paste0('fisheries_environment_matched_', source, '_', release, '_', bathy_suffix, suffix, '.csv'))
    write.csv(df, file = matched_out_path, row.names = FALSE)
    
    log_info("{name}: Initial merged dataframe matched and saved successfully.")
    df
  }, error = function(e) {
    log_error("{name}: Failed to match fisheries and environmental data: {e$message}")
    return(NULL)
  })
  
  if (is.null(matched_df)) return(NULL) # Graceful early exit

  # --- Step 3: Remove Correlated Variables ---
  final_df <- tryCatch({
    if (rm_corr) {
      log_info("{name}: Correlated variables check initialized...")
      
      # Determine variable names based on presence of static variables
      all_var_names <- if (add_static) c(names(env_rasters), names(static_variables)) else names(env_rasters)
      
      dfC <- remove_corr(matched_df, var_names = all_var_names)
      
      corr_out_path <- file.path(species_dir, paste0('fisheries_environment_', corr_suffix, '_', source, '_', release, '_', bathy_suffix, suffix, '.csv'))
      write.csv(dfC, file = corr_out_path, row.names = FALSE)
      
      log_info("{name}: Multi-collinear variables removed. Clean matched dataframe saved.")
      dfC
    } else {
      log_info("{name}: Skipping correlation reduction step as rm_corr == FALSE.")
      matched_df # Pass unedited matched dataframe downstream
    }
  }, error = function(e) {
    log_error("{name}: Failed correlation check step: {e$message}. Attempting to pass matched data frame down without correlation reduction.")
    matched_df # Fallback to matched dataframe on error instead of breaking execution
  })
  
  # --- Step 4: Split & Save Training and Test Datasets ---
  tryCatch({
    log_info("{name}: Splitting dataset into training and test datasets...")
    
    training <- final_df[final_df$year >= training_years[1] & final_df$year <= training_years[2], ]
    test     <- final_df[final_df$year >= test_years[1]     & final_df$year <= test_years[2], ]
    
    write.csv(training, file = training_name, row.names = FALSE)
    write.csv(test,     file = test_name,     row.names = FALSE)
    
    log_info("{name}: SUCCESS! Training and test data files generated successfully.")
  }, error = function(e) {
    log_error("{name}: Failed during training/test dataset split and write operations: {e$message}")
  })

}

